version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql:5.7.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_codeigniter
    ports:
      - "9906:3306"
